name: On Commit

# Run this workflow every time a new commit pushed to your repository
on: push

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: dotnet restore
        run: dotnet restore

      - name: dotnet build
        run: dotnet build --configuration Release --no-restore

      - name: dotnet test
        run: dotnet test --no-restore
